DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS ratings;
DROP TABLE IF EXISTS tag;
DROP TABLE IF EXISTS restaurant;
DROP TABLE IF EXISTS profile;

CREATE TABLE profile (
profileId INT UNSIGNED AUTO_INCREMENT NOT NULL,
userName VARCHAR(128) NOT NULL,
userSalt CHAR(64) NOT NULL,
userHash CHAR(128) NOT NULL,
PRIMARY KEY (profileId)
);

CREATE TABLE restaurant(
restId INT UNSIGNED AUTO_INCREMENT NOT NULL,
restName VARCHAR(128) NOT NULL,
PRIMARY KEY (restId)
);

CREATE TABLE tag(
tagId INT UNSIGNED AUTO_INCREMENT NOT NULL,
tagName VARCHAR(64),
PRIMARY KEY (tagId)
);

CREATE TABLE ratings (
restId INT UNSIGNED NOT NULL,
profileId INT UNSIGNED NOT NULL,
rateService TINYINT UNSIGNED,
rateFood TINYINT UNSIGNED,
rateAmbience TINYINT UNSIGNED,
rateValue TINYINT UNSIGNED,
FOREIGN KEY (restId) REFERENCES restaurants(restId),
FOREIGN KEY (profileId) REFERENCES profile(profileId),
PRIMARY KEY (restId, profileId)
);

CREATE TABLE reviews (
restId INT UNSIGNED NOT NULL,
profileId INT UNSIGNED NOT NULL,
tagName VARCHAR (64),
FOREIGN KEY (profileId) REFERENCES profile (profileId),
FOREIGN KEY (restId) REFERENCES restaurants (restId),
PRIMARY KEY (profileId, restId)
);